<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        DB::table('books')->insert([
            [
                'title' => 'The Briar Club: A Novel',
                'author' => 'Kate Quinn',
                'description' => 'test',
                'image' => 'briar.jpg',
                'price' => '20',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'Nexus: A Brief History of Information Networks from the Stone Age to AI',
                'author' => 'Yuval Noah Harari',
                'description' => 'test',
                'image' => 'nexus.jpg',
                'price' => '33.75',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'The Knowing: The Enduring Legacy of Residential Schools',
                'author' => 'Tanya Talaga',
                'description' => 'test',
                'image' => 'knowing.jpg',
                'price' => '39.99',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'real ones: a novel',
                'author' => 'Katherena Vermette',
                'description' => 'test',
                'image' => 'real.jpg',
                'price' => '35',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'The Ministry of Time: A Novel',
                'author' => 'Kaliane Bradley',
                'description' => 'test',
                'image' => 'ministry.jpg',
                'price' => '25.99',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'A Song to Drown Rivers: Deluxe Edition',
                'author' => 'Ann Liang',
                'description' => 'test',
                'image' => 'song.jpg',
                'price' => '42',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'James: A Novel',
                'author' => 'Percival Everett',
                'description' => 'test',
                'image' => 'james.png',
                'price' => '25',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'The God of the Woods: A Novel',
                'author' => 'Liz Moore',
                'description' => 'test',
                'image' => 'god.jpg',
                'price' => '39.99',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'The Capital of Dreams',
                'author' => 'Heather O Neill',
                'description' => 'test',
                'image' => 'capital.jpg',
                'price' => '34.99',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'The Women: A Novel',
                'author' => 'Kristin Hannah',
                'description' => 'test',
                'image' => 'women.jpg',
                'price' => '32',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'Men Have Called Her Crazy: A Memoir',
                'author' => 'Anna Marie Tendler',
                'description' => 'test',
                'image' => 'men.jpg',
                'price' => '39.99',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'Knife: Meditations After an Attempted Murder',
                'author' => 'Salman Rushdie',
                'description' => 'test',
                'image' => 'knife.jpg',
                'price' => '34.95',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'The Notebook: A History of Thinking on Paper',
                'author' => 'Roland Allen',
                'description' => 'test',
                'image' => 'notebook.jpg',
                'price' => '26.95',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'Reconciling History: A Story of Canada',
                'author' => 'Jody Wilson-raybould',
                'description' => 'test',
                'image' => 'reconciling.jpg',
                'price' => '39.95',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'All the Colors of the Dark: A Read with Jenna Pick: New York Times Bestselling Author of We Begin at the End',
                'author' => 'Chris Whitaker',
                'description' => 'test',
                'image' => 'colors.jpg',
                'price' => '27',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'Hair for Men: A Novel',
                'author' => 'Michelle Winters',
                'description' => 'test',
                'image' => 'hair.jpg',
                'price' => '23.99',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'When the Moon Hatched: A Novel',
                'author' => 'SARAH A. PARKER',
                'description' => 'test',
                'image' => 'moon.jpg',
                'price' => '25.99',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'Funny Story',
                'author' => 'Emily Henry',
                'description' => 'test',
                'image' => 'funny.jpg',
                'price' => '39',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'Home and Away',
                'author' => 'Mats Sundin',
                'description' => 'test',
                'image' => 'home.jpg',
                'price' => '39.99',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'This Summer Will Be Different',
                'author' => 'Carley Fortune',
                'description' => 'test',
                'image' => 'summer.jpg',
                'price' => '24.95',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'Heartless Hunter: The Crimson Moth: Book 1',
                'author' => 'Kristen Ciccarelli',
                'description' => 'test',
                'image' => 'heartless.jpg',
                'price' => '27',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'Medicine Wheel for the Planet: A Journey toward Personal and Ecological Healing',
                'author' => 'Jennifer Grenz',
                'description' => 'test',
                'image' => 'medicine.jpg',
                'price' => '34',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'Long Island: A Novel',
                'author' => 'Colm Toibin',
                'description' => 'test',
                'image' => 'long.jpg',
                'price' => '36',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'What Have You Done? (Indigo Exclusive Edition)',
                'author' => 'Shari Lapena',
                'description' => 'test',
                'image' => 'what.jpg',
                'price' => '26.95',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'Wild Love (Standard Edition)',
                'author' => 'Elsie Silver',
                'description' => 'test',
                'image' => 'wild.jpg',
                'price' => '21.59',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'The Side Gardener: Recipes & Notes from My Garden',
                'author' => 'Rosie Daykin',
                'description' => 'test',
                'image' => 'gardener.jpg',
                'price' => '45',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'The Message',
                'author' => 'Ta-nehisi Coates',
                'description' => 'test',
                'image' => 'message.jpg',
                'price' => '39.99',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'A Great Country (Indigo Exclusive Edition): A Novel',
                'author' => 'Shilpi Somaya Gowda',
                'description' => 'test',
                'image' => 'great.jpg',
                'price' => '29.95',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'Framed: Astonishing True Stories of Wrongful Convictions',
                'author' => 'John Grisham',
                'description' => 'test',
                'image' => 'framed.jpg',
                'price' => '29.96',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'The Boyfriend',
                'author' => 'Freida Mcfadden',
                'description' => 'test',
                'image' => 'boyfriend.jpg',
                'price' => '21.59',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'Rogers v. Rogers: The Battle for Control of Canada s Telecom Empire',
                'author' => 'Alexandra Posadzki',
                'description' => 'test',
                'image' => 'rogers.jpg',
                'price' => '38.95',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
            [
                'title' => 'Everyone on This Train Is a Suspect: A Novel',
                'author' => 'Benjamin Stevenson',
                'description' => 'test',
                'image' => 'everyone.jpg',
                'price' => '25.99',
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ],
        ]);

        for ($i=1; $i < 100; $i++) {
            DB::table('purchases')->insert([
                'book_id' => rand(1, 32),
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
        ]);
        }

    }
}
